#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Apr 22 21:04:14 2019

@author: maachou
"""

from sklearn.datasets.samples_generator import make_blobs
import matplotlib.pyplot as plt
from KNN import KNN


from sklearn.model_selection import train_test_split
X,Y = make_blobs(cluster_std=1,random_state=20,n_samples=300,centers=6)
X_train,X_test,y_train,y_test=train_test_split(X,Y)
Knn=KNN(n_neighbors=3)
Knn.fit(X_train,y_train)
y_pred=Knn.predict(X_test).reshape((-1,))
plt.scatter(X_test[:,0],X_test[:,1],c=y_pred)
print(Knn.score(X_test,y_test))