#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Apr 23 17:35:37 2019

@author: maachou
"""

from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from linear import linear_regression   
from LWR import LWR


 
Data=load_boston()
X=Data.data
Y=Data.target
X_train,X_test,y_train,y_test=train_test_split(X,Y)

Classifier=LWR()
Classifier.fit(X_train,y_train)

print(Classifier.score(X_test,y_test))